//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAIL_BILLS
    {
        public int dbid { get; set; }
        public Nullable<int> bid { get; set; }
        public Nullable<int> iid { get; set; }
        public int amount { get; set; }
    
        public virtual BILL BILL { get; set; }
        public virtual ITEM ITEM { get; set; }
    }
}
