//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITEM()
        {
            this.DETAIL_BILLS = new HashSet<DETAIL_BILLS>();
            this.DETAIL_SHIPMENTS = new HashSet<DETAIL_SHIPMENTS>();
        }
    
        public int iid { get; set; }
        public Nullable<int> titemid { get; set; }
        public string nameitem { get; set; }
        public long price { get; set; }
        public int amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL_BILLS> DETAIL_BILLS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL_SHIPMENTS> DETAIL_SHIPMENTS { get; set; }
        public virtual TYPE_ITEMS TYPE_ITEMS { get; set; }
    }
}
