//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrinkManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIPMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SHIPMENT()
        {
            this.DETAIL_SHIPMENTS = new HashSet<DETAIL_SHIPMENTS>();
        }
    
        public int shid { get; set; }
        public Nullable<System.DateTime> tradingdate { get; set; }
        public Nullable<int> censor { get; set; }
        public Nullable<int> sid { get; set; }
        public string rate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL_SHIPMENTS> DETAIL_SHIPMENTS { get; set; }
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
